swagger: "2.0"
info:
  description: Swagger description file for defining the RestAPI endpoints for Services
  version: "1.0.0"
  title: RB_PS-EC_HyApi_Services
consumes:
  - application/json
produces:
  - application/json


basePath: /smortCard

securityDefinitions:
  apiKey:
    type: apiKey
    x-apikeyInfoFunc: Profiles.basic_auth
    in: query
    name: accessID

#####################################################################################################
####################################### EndPoints' Description ###################################### 
#####################################################################################################
paths:
  /profile/{profileID}:
    get:
      operationId: Profiles.getProfile
      tags:
        - SmartCard
      summary: Returns the user profile based on the accessID
      parameters:
        - name: profileID
          in: path
          description: ID of the profile
          type: string
          required: True
      responses:
        200:
          description: Successfully retrieved the user profile
          schema:
            type: array
            items:
              properties:
                FirstName :
                  type: string
                LastName:
                  type: string
                Instagram:
                  type: string
                facebook:
                  type: string
                linkedin:
                  type: string
